workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      python: 3.10.0
    scripts:
      - name: Install dependencies
        script: |
          pip install buildozer cython==0.29.33
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libffi-dev libssl-dev
      - name: Build APK
        script: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          buildozer android debug
    artifacts:
      - bin/*.apk
